# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoprocesadorDeIUF
                                 A QGIS plugin
 Este plugin genera un mapa de IUF según el método escogido.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-02
        copyright            : (C) 2026 by Adrià Barreiro Franquet
        email                : adriba2105@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoprocesadorDeIUF class from file GeoprocesadorDeIUF.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geoprocesador_de_iuf import GeoprocesadorDeIUF
    return GeoprocesadorDeIUF(iface)
