# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoprocesadorDeIUF
                                 A QGIS plugin
 Este plugin genera un mapa de IUF según el método escogido.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-02
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Adrià Barreiro Franquet
        email                : adriba2105@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import time, os, subprocess, processing, glob
from qgis.core import QgsProject, QgsProcessingFeedback, QgsVectorLayer, QgsRasterLayer, QgsSpatialIndex, QgsFeatureRequest
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from osgeo import gdal
from collections import Counter
import numpy as np
from .resources import *
from .geoprocesador_de_iuf_dialog import GeoprocesadorDeIUFDialog


class GeoprocesadorDeIUF:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GeoprocesadorDeIUF_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Geoprocesador De IUF')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GeoprocesadorDeIUF', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/geoprocesador_de_iuf/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Geoprocesador de IUF'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Geoprocesador De IUF'),
                action)
            self.iface.removeToolBarIcon(action)

    def log(self, mensaje):
            """Función auxiliar para escribir en el log de la interfaz y actualizar la barra de progreso"""
            self.dlg.txtLog.append(mensaje)
            QCoreApplication.processEvents()

    def run(self):
        if self.first_start == True:
            self.first_start = False
            self.dlg = GeoprocesadorDeIUFDialog()
            self.dlg.boton_iniciar.clicked.connect(self.ejecutar_geoprocesos) #Cuando se pulse el botón "OK" de la UI, se ejecutará la función 'ejecutar_geoprocesos'
            self.dlg.boton_cancelar.clicked.connect(self.cancelar_geoprocesos)
            self.dlg.boton_cerrar.clicked.connect(self.dlg.close)

        self.dlg.show()
        self.dlg.exec_()

    def cancelar_geoprocesos(self):
        """Esta función se lanza al pulsar el botón Cancelar"""
        if hasattr(self, 'cancelado') and self.cancelado == True:
            return
        self.dlg.progressBar.setValue(0)
        self.dlg.txtLog.clear()
        self.log("Proceso abortado por el usuario.")
        self.cancelado = True
        self.dlg.boton_iniciar.setEnabled(True)
        self.dlg.selectorCapaEdificaciones.setEnabled(True)
        self.dlg.selectorCapaCombustible.setEnabled(True)
        self.dlg.metodoAlcasena.setEnabled(True)
        self.dlg.metodoLampinMaillet.setEnabled(True)
        self.dlg.directorio_final.setEnabled(True)
        self.dlg.ResultadosIntermedios.setEnabled(True)
        if hasattr(self, 'feedback') and self.feedback is not None:
            self.feedback.cancel()

    def ejecutar_geoprocesos(self):
        """Esta función se lanza al pulsar OK"""

        tiempo_inicio = time.time()

        self.dlg.boton_iniciar.setEnabled(False)
        self.dlg.selectorCapaEdificaciones.setEnabled(False)
        self.dlg.selectorCapaCombustible.setEnabled(False)
        self.dlg.metodoAlcasena.setEnabled(False)
        self.dlg.metodoLampinMaillet.setEnabled(False)
        self.dlg.directorio_final.setEnabled(False)
        self.dlg.ResultadosIntermedios.setEnabled(False)

        self.cancelado = False
        self.feedback = QgsProcessingFeedback()
        def actualizar_barra(progreso):
            self.dlg.progressBar.setValue(int(progreso))
            QCoreApplication.processEvents()
        self.feedback.progressChanged.connect(actualizar_barra)

        ids_monte = '121,122,200,210,222,223,224,231,232,251,252,253,254,255,256,257,258,259,260,241,280,290,300,301,302,310,312,313,316,320'
        
        #> 1. Reiniciar la interfaz
        self.dlg.txtLog.clear()
        self.dlg.progressBar.setValue(0)
        self.log("Iniciando lectura de datos...")

        #> 2. Leer las capas seleccionadas
        capa_edif = self.dlg.selectorCapaEdificaciones.currentLayer()
        capa_comb = self.dlg.selectorCapaCombustible.currentLayer()
        if not capa_edif or not capa_comb:
            self.log("ERROR: Faltan capas por seleccionar.")
            self.dlg.boton_iniciar.setEnabled(True)
            self.dlg.selectorCapaEdificaciones.setEnabled(True)
            self.dlg.selectorCapaCombustible.setEnabled(True)
            self.dlg.metodoAlcasena.setEnabled(True)
            self.dlg.metodoLampinMaillet.setEnabled(True)
            self.dlg.directorio_final.setEnabled(True)
            self.dlg.ResultadosIntermedios.setEnabled(True)
            return
        self.log(f"> Capa de edificaciones: {capa_edif.name()}")
        self.log(f"> Capa de combustible: {capa_comb.name()}")

        #> 3. Leer el método elegido
        if self.dlg.metodoAlcasena.isChecked():
            metodo = "Alcassena et al."
        elif self.dlg.metodoLampinMaillet.isChecked():
            metodo = "Lampin-Maillet et al."
        else:
            self.log("ERROR: Se debe seleccionar un método de cálculo.")
            self.dlg.boton_iniciar.setEnabled(True)
            self.dlg.selectorCapaEdificaciones.setEnabled(True)
            self.dlg.selectorCapaCombustible.setEnabled(True)
            self.dlg.metodoAlcasena.setEnabled(True)
            self.dlg.metodoLampinMaillet.setEnabled(True)
            self.dlg.directorio_final.setEnabled(True)
            self.dlg.ResultadosIntermedios.setEnabled(True)
            return
        self.log(f"> Método seleccionado: {metodo}")

        #> 4. Leer si queremos resultados intermedios
        intermedios = self.dlg.ResultadosIntermedios.isChecked()
        self.log(f"> Mostrar intermedios: {intermedios}")

        #> 5. Leer el directorio de salida
        ruta_salida = self.dlg.directorio_final.filePath()
        if not ruta_salida:
            self.log("ERROR: Debes indicar un archivo de salida para guardar el mapa IUF.")
            self.dlg.boton_iniciar.setEnabled(True)
            self.dlg.selectorCapaEdificaciones.setEnabled(True)
            self.dlg.selectorCapaCombustible.setEnabled(True)
            self.dlg.metodoAlcasena.setEnabled(True)
            self.dlg.metodoLampinMaillet.setEnabled(True)
            self.dlg.directorio_final.setEnabled(True)
            self.dlg.ResultadosIntermedios.setEnabled(True)
            return
        self.log(f"> Archivo de salida: {ruta_salida}")

        self.log("----------------------------------------------------------------")

        self.log("Aligerando temporalmente las capas de entrada...")
        capa_edif = processing.run("native:retainfields", {
            'INPUT': capa_edif,
            'FIELDS': ['id'],
            'OUTPUT': 'TEMPORARY_OUTPUT'
        }, feedback=self.feedback)['OUTPUT']
        if self.cancelado: return
        capa_comb = processing.run("native:retainfields", {
            'INPUT': capa_comb,
            'FIELDS': ['ID_COBERTURA_MAX'], 
            'OUTPUT': 'TEMPORARY_OUTPUT'
        }, feedback=self.feedback)['OUTPUT']
        if self.cancelado: return

        processing.run("native:createspatialindex", {'INPUT': capa_edif}, feedback=self.feedback)
        processing.run("native:createspatialindex", {'INPUT': capa_comb}, feedback=self.feedback)

        #> 6.1. MÉTODO ALCASENA
        if metodo == "Alcassena et al.":

            #> 6.1.1. Calcular el centroide de cada edificio:
            self.log("-> Calculando centroides de las edificaciones... (1/13)") if intermedios else None
            self.log("--> Calculando centroides...")
            capa_centroides = processing.run("native:centroids", {
                'INPUT': capa_edif,
                'ALL_PARTS': False,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            processing.run("native:createspatialindex", {'INPUT': capa_centroides}, feedback=self.feedback)
            if self.cancelado: return
            
            #> 6.1.2. Crear una cuadrícula de 150x150m:
            self.log("-> Creando cuadrícula de 150x150m... (2/13)") if intermedios else None
            bb = capa_comb.extent() #se toma la extensión de la capa de combustible para asegurar que cubre toda el área de estudio
            capa_cuadricula = processing.run("native:creategrid", {
                'TYPE': 2,
                'EXTENT': f"{bb.xMinimum()},{bb.xMaximum()},{bb.yMinimum()},{bb.yMaximum()}",
                'HSPACING': 150,
                'VSPACING': 150,
                'HOVERLAY': 0,
                'VOVERLAY': 0,
                'CRS': capa_edif.crs().authid(),
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            processing.run("native:createspatialindex", {'INPUT': capa_cuadricula}, feedback=self.feedback)
            if self.cancelado: return

            #> 6.1.3. Calcular la densidad de edificaciones en cada celda de la cuadricula (edificios / km^2):
            self.log("-> Calculando densidad de edificaciones en cada celda... (3/13)") if intermedios else None
            self.log("--> Contando...") if intermedios else None
            capa_cuadricula = processing.run("native:countpointsinpolygon", {
                'POLYGONS': capa_cuadricula,
                'POINTS': capa_centroides,
                'FIELD': 'edificios',
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            self.log("--> Calculando...") if intermedios else None
            capa_cuadricula = processing.run("native:fieldcalculator", {
                'INPUT': capa_cuadricula,
                'FIELD_NAME': 'densidad',
                'FIELD_TYPE': 0,
                'FIELD_LENGTH': 10,
                'FIELD_PRECISION': 2,
                'NEW_FIELD': True,
                'FORMULA': '"edificios" / 0.0225', # 150m x 150m = 0.0225 km^2
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            processing.run("native:createspatialindex", {'INPUT': capa_cuadricula}, feedback=self.feedback) #tras native:fieldcalculator se pierde el spatial index
            if self.cancelado: return

            #> 6.1.4. Clasificar cada cuadrícula en 3 clases de densidad (muy_baja, baja, medio_alta):
            self.log("-> Clasificando la densidad de cada celda... (4/13)") if intermedios else None
            capa_cuadricula = processing.run("native:fieldcalculator", {
                'INPUT': capa_cuadricula,
                'FIELD_NAME': 'densidad_clase',
                'FIELD_TYPE': 2,
                'FIELD_LENGTH': 16,
                'FIELD_PRECISION': 0,
                'NEW_FIELD': True,
                'FORMULA': """
                                CASE
                                    WHEN "densidad" = 0 THEN NULL
                                    WHEN "densidad" > 0 AND "densidad" < 6.18 THEN 'muy_baja'
                                    WHEN "densidad" >= 49.42 THEN 'medio_alta'
                                    ELSE 'baja'
                                END
                            """,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            processing.run("native:createspatialindex", {'INPUT': capa_cuadricula}, feedback=self.feedback) #tras native:fieldcalculator se pierde el spatial index
            if self.cancelado: return
            
            #> 6.1.5. Reclasificar la capa de combustible (siose) en 2 clases (vegetado y no_vegetado):
            self.log("-> Reclasificando los usos del suelo... (5/13)") if intermedios else None
            self.log("--> Reclasificando...")
            capa_comb = processing.run("native:fieldcalculator", {
                'INPUT': capa_comb,
                'FIELD_NAME': 'contenido',
                'FIELD_TYPE': 2,
                'FIELD_LENGTH': 16,
                'FORMULA': f"if(\"ID_COBERTURA_MAX\" IN ({ids_monte}), 'vegetado', 'no_vegetado')",
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            processing.run("native:createspatialindex", {'INPUT': capa_comb}, feedback=self.feedback) #tras native:fieldcalculator se pierde el spatial index
            if self.cancelado: return

            #> 6.1.6. Calcular si cada celda contiene mayoritariamente suelo vegetado o no vegetado:
            self.log("-> Calculando el contenido mayoritario de cada celda... (6/13)") if intermedios else None
            self.log("--> Extrayendo solo las partes de la capa de combustible que son vegetadas...") if intermedios else None
            capa_vegetada = processing.run("native:extractbyattribute", {
                'INPUT': capa_comb,
                'FIELD': 'contenido',
                'OPERATOR': 0,
                'VALUE': 'vegetado',
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            processing.run("native:createspatialindex", {'INPUT': capa_vegetada}, feedback=self.feedback)
            if self.cancelado: return
            self.log("--> Optimizando vegetación...")
            capa_vegetada = processing.run("native:subdivide", {
                'INPUT': capa_vegetada,
                'MAX_VERTICES': 1000,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            self.log("--> Comprobando geometrias...") if intermedios else None
            capa_vegetada = processing.run("native:fixgeometries", {
                'INPUT': capa_vegetada,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            self.log("--> Intersectando la capa de vegetado con la cuadrícula...") if intermedios else None
            capa_cuadricula = processing.run("native:calculatevectoroverlaps", {
                'INPUT': capa_cuadricula,
                'LAYERS': [capa_vegetada],
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT'] #cuello de botella aquí
            if self.cancelado: return
            self.log("--> Determinando el contenido mayoritario en cada celda...") if intermedios else None
            for f in capa_cuadricula.fields():
                if f.name().endswith('_pc'):
                    nombre_campo_pc = f.name()
                    break
            capa_cuadricula = processing.run("native:fieldcalculator", {
                'INPUT': capa_cuadricula,
                'FIELD_NAME': 'contenido_predominante',
                'FIELD_TYPE': 2,
                'FIELD_LENGTH': 16,
                'FIELD_PRECISION': 0,
                'NEW_FIELD': True,
                'FORMULA': f"IF(COALESCE(\"{nombre_campo_pc}\", 0) >= 50, 'vegetado', 'no_vegetado')",
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            processing.run("native:createspatialindex", {'INPUT': capa_cuadricula}, feedback=self.feedback) #tras native:fieldcalculator se pierde el spatial index
            if self.cancelado: return

            #> 6.1.7. Combinar poligonos de contenido vegetado:
            self.log("-> Combinando los polígonos de contenido vegetado... (7/13)") if intermedios else None
            capa_vegetada = processing.run("gdal:dissolve", {
                'INPUT': capa_vegetada,
                'GEOMETRY': 'geom',
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT'] #el algoritmo de gdal es más rapido que el nativo de QGIS
            if self.cancelado: return
            capa_vegetada = processing.run("native:multiparttosingleparts", {
                'INPUT': capa_vegetada,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            capa_vegetada.setName("vegetacion_considerada")
            QgsProject.instance().addMapLayer(capa_vegetada) if intermedios else None

            #> 6.1.8. Identificar montes de >5km^2:
            self.log("-> Identificando montes de más de 5 km^2... (8/13)") if intermedios else None
            capa_montes = processing.run("native:extractbyexpression", {
                'INPUT': capa_vegetada,
                'EXPRESSION': '$area > 5000000', #5 km^2 = 5000000 m^2
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            processing.run("native:createspatialindex", {'INPUT': capa_montes}, feedback=self.feedback)
            if self.cancelado: return
            capa_montes.setName("montes_mayores_5km2")
            QgsProject.instance().addMapLayer(capa_montes) if intermedios else None

            #> 6.1.9. Calcular el radio de afectación por pavesas (embers)
            self.log("-> Calculando el radio de afectación por pavesas... (9/13)") if intermedios else None
            capa_buffer_pavesas = processing.run("gdal:buffervectors", {
                'INPUT': capa_montes,
                'GEOMETRY': 'geom',
                'DISTANCE': 2000, #según Alcassena et al., el radio de afectación por pavesas es de 2 km
                'DISSOLVE': True,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT'] #el algoritmo de gdal es más rapido que el nativo de QGIS
            capa_buffer_pavesas = QgsVectorLayer(capa_buffer_pavesas, "radio_afectacion_pavesas", "ogr")
            processing.run("native:createspatialindex", {'INPUT': capa_buffer_pavesas}, feedback=self.feedback)
            if self.cancelado: return
            QgsProject.instance().addMapLayer(capa_buffer_pavesas) if intermedios else None

            #> 6.1.10. Añadir a cada celda de la cuadrícula la información de si intersecta o no con el radio de afectación por pavesas:
            self.log("-> Añadiendo información de intersección con el radio de afectación... (10/13)") if intermedios else None
            self.log("--> Preparando el cruce espacial...") if intermedios else None
            capa_buffer_pavesas = processing.run("native:fieldcalculator", {
                'INPUT': capa_buffer_pavesas,
                'FIELD_NAME': 'marca_temp',
                'FIELD_TYPE': 6,
                'NEW_FIELD': True,
                'FORMULA': True,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            processing.run("native:createspatialindex", {'INPUT': capa_buffer_pavesas}, feedback=self.feedback) #tras native:fieldcalculator se pierde el spatial index
            if self.cancelado: return
            self.log("--> Cruzando cuadrícula con zona de pavesas...") if intermedios else None
            capa_cuadricula = processing.run("native:joinattributesbylocation", {
                'INPUT': capa_cuadricula,
                'JOIN': capa_buffer_pavesas,
                'JOIN_FIELDS': ['marca_temp'],
                'METHOD': 0,
                'DISCARD_NONMATCHING': False,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            self.log("--> Evaluando resultados...") if intermedios else None
            capa_cuadricula = processing.run("native:fieldcalculator", {
                'INPUT': capa_cuadricula,
                'FIELD_NAME': 'interseccion_pavesas',
                'FIELD_TYPE': 2,
                'FIELD_LENGTH': 4,
                'NEW_FIELD': True,
                'FORMULA': "IF(\"marca_temp\" = True, 'sí', 'no')",
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            processing.run("native:createspatialindex", {'INPUT': capa_cuadricula}, feedback=self.feedback) #tras native:fieldcalculator se pierde el spatial index
            if self.cancelado: return
            capa_cuadricula = processing.run("native:deletecolumn", {
                'INPUT': capa_cuadricula,
                'COLUMN': ['marca_temp'],
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            capa_cuadricula.setName("cuadricula_resultados_intermedios")
            QgsProject.instance().addMapLayer(capa_cuadricula) if intermedios else None

            #> 6.1.11. Calcular el tipo de IUF en cada celda de la cuadrícula según la fórmula del método Alcassena et al.:
            self.log("-> Calculando el tipo de IUF en cada celda... (11/13)") if intermedios else None
            capa_resultado = processing.run("native:fieldcalculator", {
                'INPUT': capa_cuadricula,
                'FIELD_NAME': 'clase_IUF',
                'FIELD_TYPE': 2,
                'FIELD_LENGTH': 128,
                'NEW_FIELD': True,
                'FORMULA': """
                    CASE
                        -- (1) Very low and low housing density
                        WHEN "contenido_predominante" = 'no_vegetado' AND ("densidad_clase" = 'baja' OR "densidad_clase" = 'muy_baja') AND "interseccion_pavesas" = 'no' 
                            THEN 'Densidad de edificaciones baja o muy baja en terreno no vegetado'
                            
                        -- (2) Medium and high housing density
                        WHEN "contenido_predominante" = 'no_vegetado' AND "densidad_clase" = 'medio_alta' AND "interseccion_pavesas" = 'no' 
                            THEN 'Densidad de edificaciones medio_alta en terreno no vegetado'
                            
                        -- (3) Vegetated
                        WHEN "contenido_predominante" = 'vegetado' AND "densidad" = 0 
                            THEN 'Vegetado sin edificaciones'
                            
                        -- (4) Dispersed rural
                        WHEN "contenido_predominante" = 'vegetado' AND "densidad_clase" = 'muy_baja'
                            THEN 'Rural disperso'
                            
                        -- (5) Intermix WUI
                        WHEN "contenido_predominante" = 'vegetado' AND ("densidad_clase" = 'baja' OR "densidad_clase" = 'medio_alta')
                            THEN 'IUF intermix'
                            
                        -- (6) Interface WUI
                        WHEN "contenido_predominante" = 'no_vegetado' AND ("densidad_clase" = 'baja' OR "densidad_clase" = 'medio_alta') AND "interseccion_pavesas" = 'sí' 
                            THEN 'IUF interface'
                            
                        ELSE 'No clasificado' 
                    END
                """,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            processing.run("native:createspatialindex", {'INPUT': capa_resultado}, feedback=self.feedback)
            if self.cancelado: return

            #> 6.1.12. Rellenar celdas vacías según el tipo de IUF más común entre sus vecinas:
            self.log("-> Rellenando celdas vacías... (12/13)") if intermedios else None
            idx_clase = capa_resultado.fields().indexOf('clase_IUF')
            for n in range(2):
                if self.cancelado: return
                self.log(f"--> Ejecutando pasada de rellenado {n+1}/2...") if intermedios else None
                index = QgsSpatialIndex(capa_resultado.getFeatures())
                query = QgsFeatureRequest().setFilterExpression('"clase_IUF" = \'No clasificado\'')
                features_a_reparar = list(capa_resultado.getFeatures(query))
                if not features_a_reparar: break
                cambios = {}
                for f in features_a_reparar:
                    if self.cancelado: return
                    ids_vecinos = index.intersects(f.geometry().boundingBox())
                    clases_vecinas = []
                    for v_id in ids_vecinos:
                        if v_id == f.id(): continue
                        feat_v = capa_resultado.getFeature(v_id)
                        val = feat_v['clase_IUF']
                        if val and val != 'No clasificado':
                            clases_vecinas.append(val)
                    if clases_vecinas:
                        moda = Counter(clases_vecinas).most_common(1)[0][0]
                        cambios[f.id()] = {idx_clase: moda}
                if cambios:
                    capa_resultado.dataProvider().changeAttributeValues(cambios)
                    capa_resultado.updateFields()

            #> 6.1.13. Eliminar celdas que no se han podido clasificar y disolver las que sí:
            self.log("-> Eliminando y disolviendo celdas... (13/13)") if intermedios else None
            self.log("--> Extrayendo solo las celdas clasificadas...") if intermedios else None
            capa_resultado = processing.run("native:extractbyexpression", {
                'INPUT': capa_resultado,
                'EXPRESSION': '"clase_IUF" != \'No clasificado\'',
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            self.log("--> Disolviendo por clase de IUF...") if intermedios else None
            path_final = processing.run("native:dissolve", {
                'INPUT': capa_resultado,
                'FIELD': 'clase_IUF',
                'OUTPUT': ruta_salida
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            capa_final = QgsVectorLayer(path_final, "Mapa_IUF_Final", "ogr")
            processing.run("native:createspatialindex", {'INPUT': capa_final}, feedback=self.feedback)
            QgsProject.instance().addMapLayer(capa_final)

            #> FIN
            self.dlg.progressBar.setValue(100)
            QCoreApplication.processEvents()
            self.log("Geoproceso finalizado. El mapa de IUF se ha guardado en la ruta indicada. También se ha añadido al proyecto.")
            tiempo_fin = time.time()
            segundos_totales = tiempo_fin - tiempo_inicio
            horas_totales = segundos_totales / 3600
            self.log(f"Tiempo total de ejecución: {round(horas_totales, 2)} horas")

        #> 6.2. MÉTODO LAMPIN-MAILLET
        if metodo == "Lampin-Maillet et al.":
            
            #> 6.2.1. Reclasificar la capa de combustible (siose) en 2 clases (vegetado y no_vegetado):
            self.log("-> Reclasificando los usos del suelo... (1/8)") if intermedios else None
            self.log("--> Reclasificando...")
            capa_comb = processing.run("native:fieldcalculator", {
                'INPUT': capa_comb,
                'FIELD_NAME': 'contenido',
                'FIELD_TYPE': 2,
                'FIELD_LENGTH': 16,
                'FORMULA': f"if(\"ID_COBERTURA_MAX\" IN ({ids_monte}), 'vegetado', 'no_vegetado')",
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
    
            #> 6.2.2. Seleccionar edificaciones dentro de la zona de afectación por bosques:
            self.log("-> Seleccionando edificaciones dentro de la zona de afectación por bosques... (2/8)") if intermedios else None
            self.log("--> Extrayendo solo las partes de la capa de combustible que son vegetadas...") if intermedios else None
            capa_vegetada = processing.run("native:extractbyattribute", {
                'INPUT': capa_comb,
                'FIELD': 'contenido',
                'OPERATOR': 0,
                'VALUE': 'vegetado',
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            processing.run("native:createspatialindex", {'INPUT': capa_vegetada}, feedback=self.feedback)
            if self.cancelado: return
            self.log("--> Optimizando vegetación...")
            capa_vegetada = processing.run("native:subdivide", {
                'INPUT': capa_vegetada,
                'MAX_VERTICES': 1000,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            self.log("--> Comprobando geometrias...") if intermedios else None
            capa_vegetada = processing.run("native:fixgeometries", {
                'INPUT': capa_vegetada,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            capa_vegetada.setName("vegetacion_considerada")
            QgsProject.instance().addMapLayer(capa_vegetada) if intermedios else None
            self.log("--> Extrayendo edificaciones dentro del radio de afectación por bosques...") if intermedios else None
            radio_afectacion_bosques = processing.run("native:buffer", {
                'INPUT': capa_vegetada,
                'DISTANCE': 200,
                'DISSOLVE': True,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            processing.run("native:createspatialindex", {'INPUT': radio_afectacion_bosques}, feedback=self.feedback)
            if self.cancelado: return
            radio_afectacion_bosques.setName("radio_de_afectacion_bosques")
            QgsProject.instance().addMapLayer(radio_afectacion_bosques) if intermedios else None
            capa_edif_afectadas = processing.run("native:extractbylocation", {
                'INPUT': capa_edif,
                'PREDICATE': [0],
                'INTERSECT': radio_afectacion_bosques,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            processing.run("native:createspatialindex", {'INPUT': capa_edif_afectadas}, feedback=self.feedback)
            capa_edif_afectadas.setName("edificaciones_en_zona_afectacion_bosques")
            QgsProject.instance().addMapLayer(capa_edif_afectadas) if intermedios else None

            #> 6.2.3. Classificar conjuntos de edificios según el método de Lampin-Maillet et al. (2009):
            self.log("-> Clasificando conjuntos de edificios... (3/8)") if intermedios else None
            self.log("--> Calculando centroides de los afectados...") if intermedios else None
            centroides_afectados = processing.run("native:centroids", {
                'INPUT': capa_edif_afectadas,
                'ALL_PARTS': False,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            processing.run("native:createspatialindex", {'INPUT': centroides_afectados}, feedback=self.feedback)
            if self.cancelado: return
            self.log("--> Calculando buffers")
            clusters_principales = processing.run("native:buffer", {
                'INPUT': capa_edif_afectadas,
                'DISTANCE': 100/2,
                'DISSOLVE': True,
                'OUTPUT': 'TEMPORARY_OUTPUT',
                'SEPARATE_DISJOINT': True
            }, feedback=self.feedback)['OUTPUT']
            processing.run("native:createspatialindex", {'INPUT': clusters_principales}, feedback=self.feedback)
            if self.cancelado: return
            clusters_secundarios = processing.run("native:buffer", {
                'INPUT': capa_edif_afectadas,
                'DISTANCE': 30/2,
                'DISSOLVE': True,
                'OUTPUT': 'TEMPORARY_OUTPUT',
                'SEPARATE_DISJOINT': True
            }, feedback=self.feedback)['OUTPUT']
            processing.run("native:createspatialindex", {'INPUT': clusters_secundarios}, feedback=self.feedback)
            if self.cancelado: return
            self.log("--> Contando edificios agrupados") if intermedios else None
            clusters_principales =processing.run("native:countpointsinpolygon", {
                'POLYGONS': clusters_principales,
                'POINTS': centroides_afectados,
                'FIELD': 'NUM_EDIF',
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            clusters_secundarios =processing.run("native:countpointsinpolygon", {
                'POLYGONS': clusters_secundarios,
                'POINTS': centroides_afectados,
                'FIELD': 'NUM_EDIF_SEC',
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            self.log("--> Aplicando lógica...") if intermedios else None #lógica del estudio del 2009 | paper: https://scispace.com/papers/characterization-and-mapping-of-dwelling-types-for-forest-4dnifq3nd7
            clusters_principales = processing.run("native:fieldcalculator", {
                'INPUT': clusters_principales,
                'FIELD_NAME': 'TIPO_DE_CONJUNTO',
                'FIELD_TYPE': 2,
                'FIELD_LENGTH': 32,
                'FORMULA': """
                    CASE 
                        WHEN "NUM_EDIF" >= 2 AND "NUM_EDIF" <= 3 THEN 'Viviendas aisladas'
                        WHEN "NUM_EDIF" >= 4 AND "NUM_EDIF" <= 50 THEN 'Viviendas dispersas'
                        WHEN "NUM_EDIF" > 50 THEN 'Viviendas agrupadas'
                        ELSE 'No clasificado'
                    END
                """,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT'] #No clasificado --> Solo 1 edificación o error
            if self.cancelado: return
            clusters_secundarios = processing.run("native:fieldcalculator", {
                'INPUT': clusters_secundarios,
                'FIELD_NAME': 'SUBTIPO_DE_CONJUNTO',
                'FIELD_TYPE': 2,
                'FIELD_LENGTH': 32,
                'FORMULA': """
                    CASE 
                        WHEN "NUM_EDIF_SEC" < 10 THEN 'Agrupacion densa'
                        WHEN "NUM_EDIF_SEC" >= 10 THEN 'Agrupacion muy densa'
                        ELSE 'Sin subclase'
                    END
                """,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            self.log("--> Uniendo resultados...") if intermedios else None
            buffers_union =processing.run("native:union", {
                'INPUT': clusters_principales,
                'OVERLAY': clusters_secundarios,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            processing.run("native:createspatialindex", {'INPUT': buffers_union}, feedback=self.feedback)
            if self.cancelado: return
            buffers_union.setName("conjuntos_de_edificaciones_clasificadas")
            QgsProject.instance().addMapLayer(buffers_union) if intermedios else None

            #> 6.2.4. Rasterizar la capa de vegetación
            self.log("-> Rasterizando capa de vegetación... (4/8)") if intermedios else None
            resolucion = 5 #valor totalmente dependiente del entorno de ejecución.
            capa_vegetada_raster_path = processing.run("gdal:rasterize", {
                'INPUT': capa_vegetada,
                'BURN': 1, #pixel=1 --> vegetado
                'INIT': 0, #pixel=0 --> no vegetado
                'UNITS': 1,
                'WIDTH': resolucion,
                'HEIGHT': resolucion,
                'DATA_TYPE': 1,
                'NODATA': -9999,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            capa_vegetada_raster = QgsRasterLayer(capa_vegetada_raster_path, "vegetacion_considerada_raster")
            QgsProject.instance().addMapLayer(capa_vegetada_raster) if intermedios else None
            
            #> 6.2.5. Calcular el AI de la capa vegetada usando FRAGSTATS
            self.log("-> Calculando el Aggregation Index de la vegetación usando Fragstats... (5/8)") if intermedios else None
            fragstats_console_path = r"C:\Program Files\Fragstats 4.2\frg_cmd.exe" #Path to FRAGSTATS console executable
            if not os.path.exists(fragstats_console_path):
                self.log("ERROR: No se encuentra el ejecutable de Fragstats (frg_cmd.exe) en C:\Program Files\Fragstats 4.2\\")
                return
            dir_path = os.path.abspath(os.path.dirname(__file__)) #directory of this file
            dir_fragstats = os.path.normpath(os.path.join(dir_path, "fragstats"))
            dir_temporal = os.path.normpath(os.path.join(dir_fragstats, "_temporal"))
            AI_model_path = os.path.normpath(os.path.join(dir_fragstats, "Agregation_Index_Fragstats_Model.fca")) #Path to the model that computes AI | Circular moving window of 20 m
            batch_file_path = os.path.normpath(os.path.join(dir_temporal, "vegetacion_AI_bachfile.fbt"))
            with open(batch_file_path, 'w') as file:
                file.write(f'{capa_vegetada_raster_path}, x, -999, x, x, 1, x, IDF_GeoTIFF')
            self.log("--> Ejecutando Fragstats en segundo plano, NO TOQUE NADA...\n") if intermedios else None
            comand = [
                fragstats_console_path,
                "-m", AI_model_path,
                "-b", batch_file_path
            ]
            try:
                result = subprocess.run(comand, capture_output=True, text=True)
                self.log(result.stdout)
                self.log(result.stderr)
            except subprocess.CalledProcessError as e:
                self.log(f"Error crítico ejecutando Fragstats: {e}")
            self.log("--> Hecho, obteniendo resultados...") if intermedios else None
            input_dir = os.path.dirname(capa_vegetada_raster_path)
            input_filename = os.path.basename(capa_vegetada_raster_path) #OUTPUT.tif
            fragstats_output_folder = f"{input_filename}_mw1" #OUTPUT.tif_mw1
            resultado_path = os.path.normpath(glob.glob(os.path.join(input_dir, fragstats_output_folder, "ai_1.tif"))[0]) #se pusca el archivo en la memoria temporal
            self.log("--> Limpiando directorio temporal...") if intermedios else None
            subprocess.run(['del', '/Q', f'{dir_temporal}\\*.fbt'], shell=True)
            capa_ai_raster = QgsRasterLayer(resultado_path, "ai_raster")
            QgsProject.instance().addMapLayer(capa_ai_raster) if intermedios else None

            #> 6.2.6. Reclasificar los valores de AI en 3 grupos
            self.log("-> Reclasificando los valores de AI... (6/8)") if intermedios else None
            ds = gdal.Open(resultado_path)
            band = ds.GetRasterBand(1)
            raster_array = band.ReadAsArray()
            nodata = band.GetNoDataValue()
            if nodata is not None:
                valid_pixels = raster_array[(raster_array > 0) & (raster_array != nodata)]
            else:
                valid_pixels = raster_array[raster_array > 0]
            median_val = np.percentile(valid_pixels, 50)
            self.log(f"--> Valor de la mediana de AI: {median_val}")
            reclass_table = [
                                0, 0, 1,            # Class 1: Exactly 0 (Zero aggregation)
                                0, median_val, 2,         # Class 2: > 0 to Median (Low aggregation)
                                median_val, 100, 3        # Class 3: > Median to 100 (High aggregation)
                            ]
            ai_reclass = processing.run("native:reclassifybytable", {
                    'INPUT_RASTER': capa_ai_raster,
                    'TABLE': reclass_table,
                    'NODATA_FOR_MISSING': True,
                    'DATA_TYPE': 1,
                    'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            ai_reclass = QgsRasterLayer(ai_reclass, "ai_raster_reclass")
            QgsProject.instance().addMapLayer(ai_reclass) if intermedios else None

            #> 6.2.7. Combinar (intersectar) las capas generadas (distribución * ai)
            self.log("-> Combinando resultados... (7/8)") if intermedios else None
            self.log("--> Vectorizando la capa ai_raster_reclass...") if intermedios else None
            ai_reclass_vector = processing.run("gdal:polygonize", {
                'INPUT': ai_reclass,
                'FIELD': 'AI_value',
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback) ['OUTPUT']
            processing.run("native:createspatialindex", {'INPUT': ai_reclass_vector}, feedback=self.feedback)
            if self.cancelado: return
            self.log("--> Intersectando conjuntos de edificaciones con valores de AI...") if intermedios else None
            resultado = processing.run("native:intersection", {
                'INPUT': buffers_union,
                'OVERLAY': ai_reclass_vector,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            processing.run("native:createspatialindex", {'INPUT': resultado}, feedback=self.feedback)
            if self.cancelado: return

            #> 6.2.8. Eliminar polígonos que no se han podido clasificar y disolver los que sí:
            self.log("-> Examinando y disolviendo resultados... (8/8)") if intermedios else None
            self.log("--> Clasificando el resultado...") if intermedios else None
            resultado = processing.run("native:fieldcalculator", {
                'INPUT': resultado,
                'FIELD_NAME': 'clase_IUF',
                'FIELD_TYPE': 2,
                'FIELD_LENGTH': 128,
                'NEW_FIELD': True,
                'FORMULA': """
                    CASE
                        WHEN "TIPO_DE_CONJUNTO" = 'Viviendas aisladas' AND "AI_value" = 1 THEN 'Viviendas aisladas + Agregación cero'
                        WHEN "TIPO_DE_CONJUNTO" = 'Viviendas dispersas' AND "AI_value" = 1 THEN 'Viviendas dispersas + Agregación cero'
                        WHEN "SUBTIPO_DE_CONJUNTO" = 'Agrupacion densa' AND "AI_value" = 1 THEN 'Agrupacion densa + Agregación cero'
                        WHEN "SUBTIPO_DE_CONJUNTO" = 'Agrupacion muy densa' AND "AI_value" = 1 THEN 'Agrupacion muy densa + Agregación cero'
                        WHEN "TIPO_DE_CONJUNTO" = 'Viviendas aisladas' AND "AI_value" = 2 THEN 'Viviendas aisladas + Agregación baja'
                        WHEN "TIPO_DE_CONJUNTO" = 'Viviendas dispersas' AND "AI_value" = 2 THEN 'Viviendas dispersas + Agregación baja'
                        WHEN "SUBTIPO_DE_CONJUNTO" = 'Agrupacion densa' AND "AI_value" = 2 THEN 'Agrupacion densa + Agregación baja'
                        WHEN "SUBTIPO_DE_CONJUNTO" = 'Agrupacion muy densa' AND "AI_value" = 2 THEN 'Agrupacion muy densa + Agregación baja'
                        WHEN "TIPO_DE_CONJUNTO" = 'Viviendas aisladas' AND "AI_value" = 3 THEN 'Viviendas aisladas + Agregación alta'
                        WHEN "TIPO_DE_CONJUNTO" = 'Viviendas dispersas' AND "AI_value" = 3 THEN 'Viviendas dispersas + Agregación alta'
                        WHEN "SUBTIPO_DE_CONJUNTO" = 'Agrupacion densa' AND "AI_value" = 3 THEN 'Agrupacion densa + Agregación alta'
                        WHEN "SUBTIPO_DE_CONJUNTO" = 'Agrupacion muy densa' AND "AI_value" = 3 THEN 'Agrupacion muy densa + Agregación alta'
                        ELSE 'Fuera de IUF'
                    END
                """,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            self.log("--> Extrayendo solo polígonos clasificados...") if intermedios else None
            resultado = processing.run("native:extractbyexpression", {
                'INPUT': resultado,
                'EXPRESSION': '"clase_IUF" != \'Fuera de IUF\'',
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            self.log("--> Reparando geometrías...") if intermedios else None
            resultado = processing.run("native:fixgeometries", {
                'INPUT': resultado,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            self.log("--> Limpiando atributos...") if intermedios else None
            resultado = processing.run("native:retainfields", {
            'INPUT': resultado,
            'FIELDS': ['clase_IUF'], 
            'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            self.log("--> Disolviendo por clase de IUF...") if intermedios else None
            resultado = processing.run("native:dissolve", {
                'INPUT': resultado,
                'FIELD': 'clase_IUF',
                'SEPARATE_DISJOINT': True,
                'OUTPUT': ruta_salida
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            capa_final = QgsVectorLayer(resultado, "Mapa_IUF_Final", "ogr")
            processing.run("native:createspatialindex", {'INPUT': capa_final}, feedback=self.feedback)
            QgsProject.instance().addMapLayer(capa_final)

            #> FIN
            self.dlg.progressBar.setValue(100)
            QCoreApplication.processEvents()
            self.log("Geoproceso finalizado. El mapa de IUF se ha guardado en la ruta indicada. También se ha añadido al proyecto.")
            tiempo_fin = time.time()
            segundos_totales = tiempo_fin - tiempo_inicio
            horas_totales = segundos_totales / 3600
            self.log(f"Tiempo total de ejecución: {round(horas_totales, 2)} horas")

        #> 6. Finalizar
        self.dlg.boton_iniciar.setEnabled(True)
        self.dlg.selectorCapaEdificaciones.setEnabled(True)
        self.dlg.selectorCapaCombustible.setEnabled(True)
        self.dlg.metodoAlcasena.setEnabled(True)
        self.dlg.metodoLampinMaillet.setEnabled(True)
        self.dlg.directorio_final.setEnabled(True)
        self.dlg.ResultadosIntermedios.setEnabled(True)
        self.dlg.progressBar.setValue(100)
        self.log("FIN.")