# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoprocesadorDeIUFDialog
                                 A QGIS plugin
 Este plugin genera un mapa de IUF según el método escogido.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-02
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Adrià Barreiro Franquet
        email                : adriba2105@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'geoprocesador_de_iuf_dialog_base.ui'))

class GeoprocesadorDeIUFDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(GeoprocesadorDeIUFDialog, self).__init__(parent)
        self.setupUi(self)
