# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoprocesadorDeIUF
                                 A QGIS plugin
 Este plugin genera un mapa de IUF según el método escogido.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-02
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Adrià Barreiro Franquet
        email                : adriba2105@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .geoprocesador_de_iuf_dialog import GeoprocesadorDeIUFDialog
import os.path


class GeoprocesadorDeIUF:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GeoprocesadorDeIUF_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Geoprocesador De IUF')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GeoprocesadorDeIUF', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/geoprocesador_de_iuf/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Este plugin genera un mapa de IUF según el método escogido.'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Geoprocesador De IUF'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = GeoprocesadorDeIUFDialog()
            self.dlg.button_box.accepted.connect(self.ejecutar_geoprocesos) #Cuando se pulse el botón "OK" de la UI, se ejecutará la función 'ejecutar_geoprocesos'

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        self.dlg.exec_()

    def ejecutar_geoprocesos(self):
        """Esta función se lanza al pulsar OK"""
        
        #> 1. Reiniciar la interfaz
        self.dlg.txtLog.clear()
        self.dlg.progressBar.setValue(0)
        self.dlg.txtLog.append("Iniciando lectura de datos...")

        #> 2. Leer las capas seleccionadas
        capa_edif = self.dlg.selectorCapaEdificaciones.currentLayer()
        capa_comb = self.dlg.selectorCapaCombustible.currentLayer()
        if not capa_edif or not capa_comb:
            self.dlg.txtLog.append("ERROR: Faltan capas por seleccionar.")
            return
        self.dlg.txtLog.append(f"> Capa de edificaciones: {capa_edif.name()}")
        self.dlg.txtLog.append(f"> Capa de combustible: {capa_comb.name()}")

        #> 3. Leer el método elegido
        if self.dlg.metodoAlcassena.isChecked():
            metodo = "Alcassena et al."
        elif self.dlg.metodoABF.isChecked():
            metodo = "ABF"
        else:
            self.dlg.txtLog.append("ERROR: Se debe seleccionar un método de cálculo.")
            return
        self.dlg.txtLog.append(f"> Método seleccionado: {metodo}")

        #> 4. Leer si queremos resultados intermedios
        intermedios = self.dlg.ResultadosIntermedios.isChecked()
        self.dlg.txtLog.append(f"> Mostrar intermedios: {intermedios}")

        # --- AQUÍ IRÁ EL GEOPROCESAMIENTO REAL MÁS ADELANTE ---

        #> X. Finalizar
        self.dlg.progressBar.setValue(100)
        self.dlg.txtLog.append("FIN.")