# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoprocesadorDeIUF
                                 A QGIS plugin
 Este plugin genera un mapa de IUF según el método escogido.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-02
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Adrià Barreiro Franquet
        email                : adriba2105@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import time, os, subprocess
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QVariant
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
import processing
from qgis.core import QgsProject, QgsSpatialIndex, QgsField, QgsProcessingFeedback, QgsVectorLayer
from .resources import *
from .geoprocesador_de_iuf_dialog import GeoprocesadorDeIUFDialog
import os.path


class GeoprocesadorDeIUF:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GeoprocesadorDeIUF_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Geoprocesador De IUF')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GeoprocesadorDeIUF', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/geoprocesador_de_iuf/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Este plugin genera un mapa de IUF según el método escogido.'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Geoprocesador De IUF'),
                action)
            self.iface.removeToolBarIcon(action)

    def log(self, mensaje):
            """Función auxiliar para escribir en el log de la interfaz y actualizar la barra de progreso"""
            self.dlg.txtLog.append(mensaje)
            QCoreApplication.processEvents()

    def run(self):
        if self.first_start == True:
            self.first_start = False
            self.dlg = GeoprocesadorDeIUFDialog()
            self.dlg.boton_iniciar.clicked.connect(self.ejecutar_geoprocesos) #Cuando se pulse el botón "OK" de la UI, se ejecutará la función 'ejecutar_geoprocesos'
            self.dlg.boton_cancelar.clicked.connect(self.cancelar_geoprocesos)
            self.dlg.boton_cerrar.clicked.connect(self.dlg.close)

        self.dlg.show()
        self.dlg.exec_()

    def cancelar_geoprocesos(self):
        """Esta función se lanza al pulsar el botón Cancelar"""
        if hasattr(self, 'cancelado') and self.cancelado == True:
            return
        self.dlg.progressBar.setValue(0)
        self.dlg.txtLog.clear()
        self.log("Proceso abortado por el usuario.")
        self.cancelado = True
        self.dlg.boton_iniciar.setEnabled(True)
        self.dlg.selectorCapaEdificaciones.setEnabled(True)
        self.dlg.selectorCapaCombustible.setEnabled(True)
        self.dlg.metodoAlcasena.setEnabled(True)
        self.dlg.metodoLampinMaillet.setEnabled(True)
        self.dlg.directorio_final.setEnabled(True)
        self.dlg.ResultadosIntermedios.setEnabled(True)
        if hasattr(self, 'feedback') and self.feedback is not None:
            self.feedback.cancel()

    def ejecutar_geoprocesos(self):
        """Esta función se lanza al pulsar OK"""

        tiempo_inicio = time.time()

        self.dlg.boton_iniciar.setEnabled(False)
        self.dlg.selectorCapaEdificaciones.setEnabled(False)
        self.dlg.selectorCapaCombustible.setEnabled(False)
        self.dlg.metodoAlcasena.setEnabled(False)
        self.dlg.metodoLampinMaillet.setEnabled(False)
        self.dlg.directorio_final.setEnabled(False)
        self.dlg.ResultadosIntermedios.setEnabled(False)

        self.cancelado = False
        self.feedback = QgsProcessingFeedback()
        def actualizar_barra(progreso):
            self.dlg.progressBar.setValue(int(progreso))
            QCoreApplication.processEvents()
        self.feedback.progressChanged.connect(actualizar_barra)

        ids_monte = '121,122,200,210,222,223,224,231,232,251,252,253,254,255,256,257,258,259,260,241,280,290,300,301,302,310,312,313,316,320'
        
        #> 1. Reiniciar la interfaz
        self.dlg.txtLog.clear()
        self.dlg.progressBar.setValue(0)
        self.log("Iniciando lectura de datos...")

        #> 2. Leer las capas seleccionadas
        capa_edif = self.dlg.selectorCapaEdificaciones.currentLayer()
        capa_comb = self.dlg.selectorCapaCombustible.currentLayer()
        if not capa_edif or not capa_comb:
            self.log("ERROR: Faltan capas por seleccionar.")
            self.dlg.boton_iniciar.setEnabled(True)
            self.dlg.selectorCapaEdificaciones.setEnabled(True)
            self.dlg.selectorCapaCombustible.setEnabled(True)
            self.dlg.metodoAlcasena.setEnabled(True)
            self.dlg.metodoLampinMaillet.setEnabled(True)
            self.dlg.directorio_final.setEnabled(True)
            self.dlg.ResultadosIntermedios.setEnabled(True)
            return
        self.log(f"> Capa de edificaciones: {capa_edif.name()}")
        self.log(f"> Capa de combustible: {capa_comb.name()}")

        #> 3. Leer el método elegido
        if self.dlg.metodoAlcasena.isChecked():
            metodo = "Alcassena et al."
        elif self.dlg.metodoLampinMaillet.isChecked():
            metodo = "Lampin-Maillet et al."
        else:
            self.log("ERROR: Se debe seleccionar un método de cálculo.")
            self.dlg.boton_iniciar.setEnabled(True)
            self.dlg.selectorCapaEdificaciones.setEnabled(True)
            self.dlg.selectorCapaCombustible.setEnabled(True)
            self.dlg.metodoAlcasena.setEnabled(True)
            self.dlg.metodoLampinMaillet.setEnabled(True)
            self.dlg.directorio_final.setEnabled(True)
            self.dlg.ResultadosIntermedios.setEnabled(True)
            return
        self.log(f"> Método seleccionado: {metodo}")

        #> 4. Leer si queremos resultados intermedios
        intermedios = self.dlg.ResultadosIntermedios.isChecked()
        self.log(f"> Mostrar intermedios: {intermedios}")

        #> 5. Leer el directorio de salida
        ruta_salida = self.dlg.directorio_final.filePath()
        if not ruta_salida:
            self.log("ERROR: Debes indicar un archivo de salida para guardar el mapa IUF.")
            self.dlg.boton_iniciar.setEnabled(True)
            self.dlg.selectorCapaEdificaciones.setEnabled(True)
            self.dlg.selectorCapaCombustible.setEnabled(True)
            self.dlg.metodoAlcasena.setEnabled(True)
            self.dlg.metodoLampinMaillet.setEnabled(True)
            self.dlg.directorio_final.setEnabled(True)
            self.dlg.ResultadosIntermedios.setEnabled(True)
            return
        self.log(f"> Archivo de salida: {ruta_salida}")

        self.log("----------------------------------------------------------------")

        #> 6.1. MÉTODO ALCASENA
        if metodo == "Alcassena et al.":

            #> 6.1.1. Calcular el centroide de cada edificio:
            self.log("-> Calculando centroides de las edificaciones... (1/13)") if intermedios else None
            capa_centroides = processing.run("native:centroids", {
                'INPUT': capa_edif,
                'ALL_PARTS': False,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            
            #> 6.1.2. Crear una cuadrícula de 150x150m:
            self.log("-> Creando cuadrícula de 150x150m... (2/13)") if intermedios else None
            bb = capa_comb.extent() #se toma la extensión de la capa de combustible para asegurar que cubre toda el área de estudio
            capa_cuadricula = processing.run("native:creategrid", {
                'TYPE': 2,
                'EXTENT': f"{bb.xMinimum()},{bb.xMaximum()},{bb.yMinimum()},{bb.yMaximum()}",
                'HSPACING': 150,
                'VSPACING': 150,
                'HOVERLAY': 0,
                'VOVERLAY': 0,
                'CRS': capa_edif.crs().authid(),
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return

            #> 6.1.3. Calcular la densidad de edificaciones en cada celda de la cuadricula (edificios / km^2):
            self.log("-> Calculando densidad de edificaciones en cada celda... (3/13)") if intermedios else None
            self.log("--> Creando índices espaciales...") if intermedios else None
            processing.run("native:createspatialindex", {'INPUT': capa_cuadricula}, feedback=self.feedback)
            processing.run("native:createspatialindex", {'INPUT': capa_centroides}, feedback=self.feedback)
            self.log("--> Contando...") if intermedios else None
            capa_cuadricula_conteo = processing.run("native:countpointsinpolygon", {
                'POLYGONS': capa_cuadricula,
                'POINTS': capa_centroides,
                'FIELD': 'edificios',
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            self.log("--> Calculando...") if intermedios else None
            capa_cuadricula_densidad = processing.run("native:fieldcalculator", {
                'INPUT': capa_cuadricula_conteo,
                'FIELD_NAME': 'densidad',
                'FIELD_TYPE': 0,
                'FIELD_LENGTH': 10,
                'FIELD_PRECISION': 2,
                'NEW_FIELD': True,
                'FORMULA': '"edificios" / 0.0225', # 150m x 150m = 0.0225 km^2
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            capa_cuadricula = capa_cuadricula_densidad

            #> 6.1.4. Clasificar cada cuadrícula en 3 clases de densidad (muy_baja, baja, medio_alta):
            self.log("-> Clasificando la densidad de cada celda... (4/13)") if intermedios else None
            capa_cuadricula_clasificada = processing.run("native:fieldcalculator", {
                'INPUT': capa_cuadricula,
                'FIELD_NAME': 'densidad_clase',
                'FIELD_TYPE': 2,
                'FIELD_LENGTH': 16,
                'FIELD_PRECISION': 0,
                'NEW_FIELD': True,
                'FORMULA': """
                                CASE
                                    WHEN "densidad" = 0 THEN NULL
                                    WHEN "densidad" > 0 AND "densidad" < 6.18 THEN 'muy_baja'
                                    WHEN "densidad" >= 49.42 THEN 'medio_alta'
                                    ELSE 'baja'
                                END
                            """,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            capa_cuadricula = capa_cuadricula_clasificada
            
            #> 6.1.5. Reclasificar la capa de combustible (siose) en 2 clases (vegetado y no_vegetado):
            self.log("-> Reclasificando los usos del suelo... (5/13)") if intermedios else None
            capa_comb_reclasificada = processing.run("qgis:executesql", {
                'INPUT_DATASOURCES': [capa_comb],
                'INPUT_QUERY': f"""
                                    SELECT *, 
                                    CASE 
                                        WHEN ID_COBERTURA_MAX IN ({ids_monte}) THEN 'vegetado' 
                                        ELSE 'no_vegetado' 
                                    END AS contenido 
                                    FROM input1
                                """,
                'GEOMETRY_FIELD': 'geometry',
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            capa_comb = capa_comb_reclasificada

            #> 6.1.6. Calcular si cada celda contiene mayoritariamente suelo vegetado o no vegetado:
            self.log("-> Calculando el contenido mayoritario de cada celda... (6/13)") if intermedios else None
            self.log("--> Extrayendo solo las partes de la capa de combustible que son vegetadas...") if intermedios else None
            capa_vegetada = processing.run("native:extractbyattribute", {
                'INPUT': capa_comb,
                'FIELD': 'contenido',
                'OPERATOR': 0,
                'VALUE': 'vegetado',
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            self.log("--> Creando índices espaciales...") if intermedios else None
            processing.run("native:createspatialindex", {'INPUT': capa_cuadricula}, feedback=self.feedback)
            processing.run("native:createspatialindex", {'INPUT': capa_vegetada}, feedback=self.feedback)
            self.log("--> Intersectando la capa de vegetado con la cuadrícula...") if intermedios else None
            capa_cuadricula_overlap = processing.run("native:calculatevectoroverlaps", {
                'INPUT': capa_cuadricula,
                'LAYERS': [capa_vegetada],
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            self.log("--> Determinando el contenido mayoritario en cada celda...") if intermedios else None
            for f in capa_cuadricula_overlap.fields():
                if f.name().endswith('_pc'):
                    nombre_campo_pc = f.name()
                    break
            formula_mayoritario = f"IF(COALESCE(\"{nombre_campo_pc}\", 0) >= 50, 'vegetado', 'no_vegetado')"
            capa_cuadricula_final = processing.run("native:fieldcalculator", {
                'INPUT': capa_cuadricula_overlap,
                'FIELD_NAME': 'contenido_predominante',
                'FIELD_TYPE': 2,
                'FIELD_LENGTH': 16,
                'FIELD_PRECISION': 0,
                'NEW_FIELD': True,
                'FORMULA': formula_mayoritario,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            capa_cuadricula = capa_cuadricula_final

            #> 6.1.7. Combinar poligonos de contenido vegetado:
            self.log("-> Combinando los polígonos de contenido vegetado... (7/13)") if intermedios else None
            self.log("--> Disolviendo...") if intermedios else None
            capa_vegetada = processing.run("qgis:executesql", {
                'INPUT_DATASOURCES': [capa_vegetada],
                'INPUT_QUERY': """
                                    SELECT ST_UnaryUnion(ST_Collect(geometry)) AS geometry 
                                    FROM input1
                                """,
                'GEOMETRY_FIELD': 'geometry',
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT'] #SQL es mucho más rápido para disolver que el algoritmo "native:dissolve" de qgis | DOC: https://jancaha.github.io/r_package_qgis/reference/qgis_executesql.html
            if self.cancelado: return
            self.log("--> Combinando...") if intermedios else None
            capa_vegetada = processing.run("native:multiparttosingleparts", {
                'INPUT': capa_vegetada,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            capa_vegetada.setName("vegetacion_considerada")
            QgsProject.instance().addMapLayer(capa_vegetada) if intermedios else None

            #> 6.1.8. Identificar montes de >5km^2:
            self.log("-> Identificando montes de más de 5 km^2... (8/13)") if intermedios else None
            capa_montes = processing.run("native:extractbyexpression", {
                'INPUT': capa_vegetada,
                'EXPRESSION': '$area > 5000000', #5 km^2 = 5000000 m^2
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            capa_montes.setName("montes_mayores_5km2")
            QgsProject.instance().addMapLayer(capa_montes) if intermedios else None

            #> 6.1.9. Calcular el radio de afectación por pavesas (embers)
            self.log("-> Calculando el radio de afectación por pavesas... (9/13)") if intermedios else None
            buffer_pavesas = processing.run("native:buffer", {
                'INPUT': capa_montes,
                'DISTANCE': 2000, #según Alcassena et al., el radio de afectación por pavesas es de 2 km | se modifica a 500m
                'DISSOLVE': True,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            buffer_pavesas.setName("radio_afectacion_pavesas")
            QgsProject.instance().addMapLayer(buffer_pavesas) if intermedios else None

            #> 6.1.10. Añadir a cada celda de la cuadrícula la información de si intersecta o no con el radio de afectación por pavesas:
            self.log("-> Añadiendo información de intersección con el radio de afectación... (10/13)") if intermedios else None
            self.log("--> Creando índices espaciales...") if intermedios else None
            processing.run("native:createspatialindex", {'INPUT': capa_cuadricula}, feedback=self.feedback)
            processing.run("native:createspatialindex", {'INPUT': buffer_pavesas}, feedback=self.feedback)
            self.log("--> Preparando el cruce espacial...") if intermedios else None
            buffer_marcado = processing.run("native:fieldcalculator", {
                'INPUT': buffer_pavesas,
                'FIELD_NAME': 'marca_temp',
                'FIELD_TYPE': 2,
                'FIELD_LENGTH': 2,
                'NEW_FIELD': True,
                'FORMULA': "'1'",
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            self.log("--> Cruzando cuadrícula con zona de pavesas...") if intermedios else None
            cuadricula_join = processing.run("native:joinattributesbylocation", {
                'INPUT': capa_cuadricula,
                'JOIN': buffer_marcado,
                'PREDICATE': [0],
                'JOIN_FIELDS': ['marca_temp'],
                'METHOD': 0,
                'DISCARD_NONMATCHING': False,
                'PREFIX': '',
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            self.log("--> Evaluando resultados...") if intermedios else None
            capa_cuadricula_sino = processing.run("native:fieldcalculator", {
                'INPUT': cuadricula_join,
                'FIELD_NAME': 'interseccion_pavesas',
                'FIELD_TYPE': 2,
                'FIELD_LENGTH': 10,
                'NEW_FIELD': True,
                'FORMULA': "IF(\"marca_temp\" = '1', 'sí', 'no')",
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            capa_cuadricula_final = processing.run("native:deletecolumn", {
                'INPUT': capa_cuadricula_sino,
                'COLUMN': ['marca_temp'],
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            capa_cuadricula = capa_cuadricula_final
            capa_cuadricula.setName("cuadricula_resultados_intermedios")
            QgsProject.instance().addMapLayer(capa_cuadricula) if intermedios else None

            #> 6.1.11. Calcular el tipo de IUF en cada celda de la cuadrícula según la fórmula del método Alcassena et al.:
            self.log("-> Calculando el tipo de IUF en cada celda... (11/13)") if intermedios else None
            capa_resultado = processing.run("native:fieldcalculator", {
                'INPUT': capa_cuadricula,
                'FIELD_NAME': 'clase_IUF',
                'FIELD_TYPE': 2,
                'FIELD_LENGTH': 128,
                'NEW_FIELD': True,
                'FORMULA': """
                    CASE
                        -- (1) Very low and low housing density
                        WHEN "contenido_predominante" = 'no_vegetado' AND ("densidad_clase" = 'baja' OR "densidad_clase" = 'muy_baja') AND "interseccion_pavesas" = 'no' 
                            THEN 'Densidad de edificaciones baja o muy baja en terreno no vegetado'
                            
                        -- (2) Medium and high housing density
                        WHEN "contenido_predominante" = 'no_vegetado' AND "densidad_clase" = 'medio_alta' AND "interseccion_pavesas" = 'no' 
                            THEN 'Densidad de edificaciones medio_alta en terreno no vegetado'
                            
                        -- (3) Vegetated
                        WHEN "contenido_predominante" = 'vegetado' AND "densidad" = 0 
                            THEN 'Vegetado sin edificaciones'
                            
                        -- (4) Dispersed rural
                        WHEN "contenido_predominante" = 'vegetado' AND "densidad_clase" = 'muy_baja'
                            THEN 'Rural disperso'
                            
                        -- (5) Intermix WUI
                        WHEN "contenido_predominante" = 'vegetado' AND ("densidad_clase" = 'baja' OR "densidad_clase" = 'medio_alta')
                            THEN 'IUF intermix'
                            
                        -- (6) Interface WUI
                        WHEN "contenido_predominante" = 'no_vegetado' AND ("densidad_clase" = 'baja' OR "densidad_clase" = 'medio_alta') AND "interseccion_pavesas" = 'sí' 
                            THEN 'IUF interface'
                            
                        ELSE 'No clasificado' 
                    END
                """,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return

            #> 6.1.12. Rellenar celdas vacías según el tipo de IUF más común entre sus vecinas:
            self.log("-> Rellenando celdas vacías... (12/13)") if intermedios else None
            for n in range(2):
                if self.cancelado: return
                self.log(f"--> Ejecutando pasada de rellenado {n+1}/2...") if intermedios else None
                processing.run("native:createspatialindex", {'INPUT': capa_resultado}, feedback=self.feedback)
                capa_rellenada = processing.run("native:fieldcalculator", {
                    'INPUT': capa_resultado,
                    'FIELD_NAME': 'clase_IUF',
                    'FIELD_TYPE': 2,
                    'FIELD_LENGTH': 32,
                    'NEW_FIELD': False,
                    'FORMULA': """
                                    CASE 
                                        WHEN "clase_IUF" = 'No clasificado' THEN
                                            COALESCE(
                                                array_first(
                                                    array_majority(
                                                        array_remove_all(
                                                            overlay_touches(@layer, "clase_IUF"), 
                                                            'No clasificado'
                                                        )
                                                    )
                                                ),
                                                'No clasificado'
                                            )
                                        ELSE "clase_IUF"
                                    END
                                """,
                    'OUTPUT': 'TEMPORARY_OUTPUT'
                }, feedback=self.feedback)['OUTPUT']
                if self.cancelado: return
                capa_resultado = capa_rellenada

            #> 6.1.13. Eliminar celdas que no se han podido clasificar y disolver las que sí:
            self.log("-> Eliminando y disolviendo celdas... (13/13)") if intermedios else None
            self.log("--> Extrayendo solo las celdas clasificadas...") if intermedios else None
            capa_resultado_clasificado = processing.run("native:extractbyexpression", {
                'INPUT': capa_resultado,
                'EXPRESSION': '"clase_IUF" != \'No clasificado\'',
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            self.log("--> Disolviendo por clase de IUF...") if intermedios else None
            path_final = processing.run("native:dissolve", {
                'INPUT': capa_resultado_clasificado,
                'FIELD': 'clase_IUF',
                'OUTPUT': ruta_salida
            }, feedback=self.feedback)['OUTPUT']
            if self.cancelado: return
            capa_final = QgsVectorLayer(path_final, "Mapa_IUF_Final", "ogr")
            processing.run("native:createspatialindex", {'INPUT': capa_final}, feedback=self.feedback) #crear índice espacial en la capa final para mejorar el rendimiento al cargarla en el proyecto
            QgsProject.instance().addMapLayer(capa_final)

            #> FIN
            self.dlg.progressBar.setValue(100)
            QCoreApplication.processEvents()
            self.log("Geoproceso finalizado. El mapa de IUF se ha guardado en la ruta indicada. También se ha añadido al proyecto.")
            tiempo_fin = time.time()
            segundos_totales = tiempo_fin - tiempo_inicio
            horas_totales = segundos_totales / 3600
            self.log(f"Tiempo total de ejecución: {round(horas_totales, 2)} horas")

        #> 6.2. MÉTODO LAMPIN-MAILLET
        if metodo == "Lampin-Maillet et al.":
            
            #> 6.2.1. Reclasificar la capa de combustible (siose) en 2 clases (vegetado y no_vegetado):
            if self.cancelado: return
            self.log("-> Reclasificando los usos del suelo... (1/x)") if intermedios else None
            capa_comb_reclasificada = processing.run("native:fieldcalculator", {
                'INPUT': capa_comb,
                'FIELD_NAME': 'contenido',
                'FIELD_TYPE': 2,
                'FIELD_LENGTH': 16,
                'FIELD_PRECISION': 0,
                'NEW_FIELD': True,
                'FORMULA': f"IF(\"ID_COBERTURA_MAX\" IN ({ids_monte}), 'vegetado', 'no_vegetado')",
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            capa_comb = capa_comb_reclasificada
    
            #> 6.2.2. Seleccionar edificaciones dentro de la zona de afectación por bosques:
            if self.cancelado: return
            self.log("-> Seleccionando edificaciones dentro de la zona de afectación por bosques... (2/x)") if intermedios else None
            self.log("--> Extrayendo solo las partes de la capa de combustible que son vegetadas...") if intermedios else None
            capa_vegetada = processing.run("native:extractbyattribute", {
                'INPUT': capa_comb,
                'FIELD': 'contenido',
                'OPERATOR': 0,
                'VALUE': 'vegetado',
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            capa_vegetada.setName("vegetacion_considerada")
            QgsProject.instance().addMapLayer(capa_vegetada) if intermedios else None
            self.log("--> Creando índices espaciales...") if intermedios else None
            processing.run("native:createspatialindex", {'INPUT': capa_edif}, feedback=self.feedback)
            processing.run("native:createspatialindex", {'INPUT': capa_vegetada}, feedback=self.feedback)
            self.log("--> Trazando el radio de afectación por bosques...") if intermedios else None
            capa_edif_buffer = processing.run("native:buffer", {
                'INPUT': capa_vegetada,
                'DISTANCE': 200,
                'DISSOLVE': True,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            self.log("--> Seleccionando las edificaciones que intersectan con el radio de afectación...") if intermedios else None
            capa_edif_afectadas = processing.run("native:extractbylocation", {
                'INPUT': capa_edif,
                'PREDICATE': [0],
                'INTERSECT': capa_edif_buffer,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            capa_edif_afectadas.setName("edificaciones_en_zona_afectacion_bosques")
            QgsProject.instance().addMapLayer(capa_edif_afectadas) if intermedios else None

            #> 6.2.3. Classificar conjuntos de edificios según el método de Lampin-Maillet et al. (2009):
            if self.cancelado: return
            self.log("-> Clasificando conjuntos de edificios... (3/x)") if intermedios else None
            self.log("--> Creando buffers...") if intermedios else None
            buffers = processing.run("native:buffer", {
                'INPUT': capa_edif_afectadas,
                'DISTANCE': 100/2,
                'DISSOLVE': True,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            self.log("--> Contando edificios agrupados") if intermedios else None
            buffers_conteo = processing.run("native:fieldcalculator", {
                'INPUT': buffers,
                'FIELD_NAME': 'NUM_EDIF',
                'FIELD_TYPE': 0,
                'NEW_FIELD': True,
                'FORMULA': f"aggregate(layer:='{capa_edif_afectadas.id()}', aggregate:='count', expression:=@id, filter:=intersects($geometry, geometry(@parent)))",
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            self.log("--> Aplicando lógica...") if intermedios else None #lógica del estudio del 2009 (SIN TENER EN CUENTA LOS 2 SUBGRUPOS DE 'Viviendas agrupadas')
            buffers_clasificados = processing.run("native:fieldcalculator", {
                'INPUT': buffers_conteo,
                'FIELD_NAME': 'TIPO_DE_CONJUNTO',
                'FIELD_TYPE': 2,
                'FIELD_LENGTH': 32,
                'FORMULA': """
                                CASE 
                                    WHEN "NUM_EDIF" >= 2 AND "NUM_EDIF" <= 3 THEN 'Viviendas aisladas'
                                    WHEN "NUM_EDIF" >= 4 AND "NUM_EDIF" <= 50 THEN 'Viviendas dispersas'
                                    WHEN "NUM_EDIF" > 50 THEN 'Viviendas agrupadas'
                                    ELSE 'No clasificado'
                                END
                            """,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            buffers_clasificados.setName("edificaciones_clasificadas")
            QgsProject.instance().addMapLayer(buffers_clasificados)

            #> 6.2.4. Rasterizar la capa de vegetación
            self.log("-> Rasterizando capa de vegetación... (4/x)") if intermedios else None
            resolucion = 5 #valor totalmente dependiente del entorno de ejecución.
            extension = capa_vegetada.extent()
            ext_str = f"{extension.xMinimum()},{extension.xMaximum()},{extension.yMinimum()},{extension.yMaximum()}"
            capa_vegetada_raster = processing.run("gdal:rasterize", {
                'INPUT': capa_vegetada,
                'BURN': 1,
                'UNITS': 1,
                'WIDTH': resolucion,
                'HEIGHT': resolucion,
                'EXTENT': ext_str,
                'DATA_TYPE': 1,
                'NODATA': -9999,
                'OUTPUT': 'TEMPORARY_OUTPUT'
            }, feedback=self.feedback)['OUTPUT']
            capa_vegetada_raster.setName("vegetacion_considerada_raster")
            QgsProject.instance().addMapLayer(capa_vegetada_raster)

            #> 6.2.5. Calcular el AI de la capa vegetada usando FRAGSTATS
            fragstats_path = r"C:\Program Files\Fragstats 4.2\frg_cmd.exe" #Path to FRAGSTATS console executable
            AI_model_path = r"fragstats\Agregation_Index_Fragstats_Model.fca" #Path to the model that computes AI

            batchfile_path = os.path.join("fragstats\_temporal", f"Feature_{id}_bachfile_raster.ftb")
            output_class_path = os.path.join("fragstats\_temporal", f"Feature_{id}_AI.class")
            with open(batchfile_path, 'w') as file:
                file.write(f"{capa_vegetada_raster}, x, 999, x, x, 1, x, IDF_GeoTIFF")
            comand = [
                fragstats_path,
                "-m", AI_model_path,
                "-b", batchfile_path,
                "-o", output_class_path
            ]
            subprocess.run(comand, check=True)
            
            #> FIN
            self.dlg.progressBar.setValue(100)
            QCoreApplication.processEvents()
            self.log("Geoproceso finalizado. El mapa de IUF se ha guardado en la ruta indicada. También se ha añadido al proyecto.")
            tiempo_fin = time.time()
            segundos_totales = tiempo_fin - tiempo_inicio
            horas_totales = segundos_totales / 3600
            self.log(f"Tiempo total de ejecución: {round(horas_totales, 2)} horas")

        #> 6. Finalizar
        self.dlg.boton_iniciar.setEnabled(True)
        self.dlg.selectorCapaEdificaciones.setEnabled(True)
        self.dlg.selectorCapaCombustible.setEnabled(True)
        self.dlg.metodoAlcasena.setEnabled(True)
        self.dlg.metodoLampinMaillet.setEnabled(True)
        self.dlg.directorio_final.setEnabled(True)
        self.dlg.ResultadosIntermedios.setEnabled(True)
        self.dlg.progressBar.setValue(100)
        self.log("FIN.")